<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/07/31 13:53:11

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=roomexpense',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
